# Generated by Django 5.0.6 on 2024-05-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='extracted_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
