# Generated by Django 5.0.6 on 2024-05-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerdocument_extracted_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
